"""initial schema: Camera, RuleConfig, RuleTypes

Revision ID: e1e2efec4d8b
Revises: 
Create Date: 2026-07-23 04:28:31.942068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e2efec4d8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_name', sa.String(length=50), nullable=False),
    sa.Column('rtsp_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive'), nullable=True),
    sa.Column('view', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RuleConfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('roi_coordinates', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive'), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['Camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RuleTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruleconfig_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=255), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ruleconfig_id'], ['RuleConfig.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RuleTypes')
    op.drop_table('RuleConfig')
    op.drop_table('Camera')
    # ### end Alembic commands ###
